FROM node:21

WORKDIR /app

# COPY package*.json ./

# RUN npm install

COPY example_input.txt ./
COPY input.txt ./
COPY red-nosed-reports.js ./

# EXPOSE 3000

CMD [ "node", "red-nosed-reports.js" ]
